### ISSUE TITLE
Status가 게임이 종료되어도 유지되는 버그

### ISSUE THREAD

**Issue by suhynnoh** [HY-CtrlS/Universal-Invaders#10]
게임 중 Status가 업그레이드되는 경우, 게임이 종료되고 새로운 게임이 시작되어도 이전 게임에서의 변경사항이 유지되는 버그가 있습니다.
이를 해결하기 위해

1. StatusManager 클래스에 파일에 있는 스텟값으로 status를 설정하는 reset()메소드를 추가하고,
2. 새로운 게임이 시작될 때 StatusManager.reset()을 호출해야할 것 같습니다.

**Comment by Geguuuul** [comment]
Core의 Case:2 들어가면서 do 전에 바로 호출해서 한번 초기화 하면 될려나요
