### ISSUE TITLE
레벨이 올라가면 스코어 8000점이 추가됨

### ISSUE THREAD

**Issue by Koominjae** [HY-CtrlS/Universal-Invaders#13]
각 레벨을 클리어 한 후 아이템 선택하고 다음 레벨로 넘어가면 적을 죽여 얻은 스코어에 8000점이 추가됨

**Comment by Koominjae** [comment]
방금 또 새 게임을 플레이 해보니 6000점씩 오르는거 보니 무조건 8000점은 아닌거 같습니다

**Comment by Geguuuul** [comment]
해당 부분은 GameScreen run() 메소드가 끝날때 hp에서 -20을 빼고 넘어가게 되는데, 그래서 hp가 100인 상태로 넘어가면 

100-20인 80에 기존에 hp 전환 전에 목숨에 따라서 추가 점수를 주는 점수가 100점이었기에 100 * 80해서 8000점이 추가되는 것입니다. 

현재 여러 기능들에서 게임의 장르부터가 바뀌다 보니 적절하지 않은 기능들이 섞여있는 경우가 있습니다. 다음 스프린트 쯤에 해당 부분 관련해서 게임을 다듬는 시간이 한 번은 있어야 할 것 같습니다.
