### ISSUE TITLE
[BUG] 32레벨 달성 시 게임 멈춤

### ISSUE THREAD

**Issue by PseudoCardiac** [HY-CtrlS/Universal-Invaders#42]
### 재현 상황

31레벨인 상태에서 경험치를 획득해 경험치가 전부 채워지는 순간 게임이 멈춤

**Comment by Geguuuul** [comment]
아이템 최대 레벨이 5레벨인데 아이템을 계속 골라서 아이템이 5레벨이 되면 items 배열에서 해당 아이템이 제거됩니다. 그 이후에도 계속 선택하여 31레벨때가 되면 30번을 골라서 아이템 6개가 모두 최대레벨에 도달해 아마 Items 배열에 아이템이 없는 상태일 겁니다. 근데 현재 아이템 고르는 메소드에 해당 부분을 체크하는 부분이 없어서 이 부분에 대한 부분을 처리하고 아이템을 모두 고른 경우의 화면 출력도 구성을 추가해줘야 할 것 같습니다. 해당 부분 작업 우선적으로 해서 PR 열겠습니다.
