### ISSUE TITLE
[BUG] 아이템 최대 레벨 도달 시 인덱스 오류 발생

### ISSUE THREAD

**Issue by Koominjae** [HY-CtrlS/Universal-Invaders#70]
### 재현 상황

한 아이템을 최대 레벨이 된 후 다음 레벨업을 통해 아이템 선택 화면으로 넘어갈 때,

### 기대 결과

버그 없음

### 실제 결과

최대 레벨이 된 아이템이 리스트에서 사라지면서 정보를 읽어 올 수 없음

### 환경

Window, jdk-21, main 브랜치

**Comment by Geguuuul** [comment]
브랜치에서 작업중입니다.

**Comment by Geguuuul** [comment]
수정완료하였습니다. https://github.com/HY-CtrlS/Universal-Invaders/pull/86
