### ISSUE TITLE
[ENHANCEMENT] 보스 스테이지 진입 포탈 진입방법 표시

### ISSUE THREAD

**Issue by suhynnoh** [HY-CtrlS/Universal-Invaders#71]
### 이유

현재 300초가 되면 나오는 포탈에 진입하는 방법을 유저에게 알리는 길이 없습니다. 이는 UX에 좋지 않은 영향을 끼칠 것으로 예상됩니다.

### 개선 방안

포탈과 아군 함선의 충돌이 일어나있을 때, "Press space to enter..."와 같이 안내 문구를 화면에 표시하면 좋을 것 같습니다.
단순하게 구현한다면, 포탈이 생기면서 안내 문구를 화면에 계속 띄우는 것도 좋을 것 같습니다.

### 추가 정보

<img width="832" alt="스크린샷 2024-12-05 15 35 32" src="https://github.com/user-attachments/assets/9b4cf269-829a-40ad-945e-6ffe4e7eee4c">

**Comment by Koominjae** [comment]
추가로 포탈과 함선이 충돌하자 마자 바로 넘어가는 것이 아니기 때문에 포탈 생성 위치를 화면 중앙으로 변경해도 괜찮을 것 같습니다.
