### ISSUE TITLE
[BUG] 체력 바 크기 오버

### ISSUE THREAD

**Issue by Koominjae** [HY-CtrlS/Universal-Invaders#73]
### 재현 상황

최대 체력 증가 아이템 선택 시

### 기대 결과

체력바가 최대 체력과 현재 체력의 비율에 맞게 그려짐

### 실제 결과

크기가 정해져있는 체력바 보더라인보다 크게 그려짐

### 환경

Window, jdk-21, main 브랜치

### 추가 정보

![image](https://github.com/user-attachments/assets/0ea0819d-9f3a-467c-82c7-4c6c4c953e64)

**Comment by PseudoCardiac** [comment]
DrawManager의 DrawLives 메서드에 전달되는 maxHp 파라미터는 GameScreen의 maxHp 속성을 그대로 가져온 건데, GameScreen.maxHp가 GameScreen 객체가 생성될 때 `getStatusManager().getMaxHp()`로 한 번 초기화되고 그 후로 갱신되지 않는 듯합니다. 적의 탄막에 충돌하거나 리젠을 통해 GameScreen 내에서 증감되는 hp와는 달리, StatusManager로만 관리되는 maxHp는 그 증감이 DrawManager까지 제대로 전달되지 않는 것으로 보입니다.

drawLives에 전달되는 maxHp 파라미터를 `status.getMaxHp()`로 대체하니 기대 결과가 나옵니다. 이대로 수정해도 괜찮을까요?

**Comment by Koominjae** [comment]
> DrawManager의 DrawLives 메서드에 전달되는 maxHp 파라미터는 GameScreen의 maxHp 속성을 그대로 가져온 건데, GameScreen.maxHp가 GameScreen 객체가 생성될 때 `getStatusManager().getMaxHp()`로 한 번 초기화되고 그 후로 갱신되지 않는 듯합니다. 적의 탄막에 충돌하거나 리젠을 통해 GameScreen 내에서 증감되는 hp와는 달리, StatusManager로만 관리되는 maxHp는 그 증감이 DrawManager까지 제대로 전달되지 않는 것으로 보입니다.
> 
> drawLives에 전달되는 maxHp 파라미터를 `status.getMaxHp()`로 대체하니 기대 결과가 나옵니다. 이대로 수정해도 괜찮을까요?

이슈 해결 가능한건 바로바로 브랜치 생성해서 해결해주시면 됩니다
