### ISSUE TITLE
[ENHANCEMENT] 밸런스 조정

### ISSUE THREAD

**Issue by Koominjae** [HY-CtrlS/Universal-Invaders#76]
### 이유

좀 더 재미있는 게임 진행과 적절한 난이도 조절이 필요하다고 느낌

### 개선 방안

데미지, 속도, 쿨다운 등 게임 진행에 있어서 수치적으로 나타내어지는 모든 부분들의 밸런스를 적절히 조절해야 함.

**Comment by Koominjae** [comment]
~~1. 보스 스테이지 가로, 세로 일자 패턴 탄막 간격 늘리기~~ (완료)
~~2. 스크린 전환 쿨다운 줄이거나 혹은 삭제~~ (완료)
~~3. 일반 스테이지 적 생성 텀 줄이기~~ (완료)
~~4. 이동속도 증가 폭 감소~~ (완료)
~~5. 궁극기 사용가능 기준치 감소~~ (완료)
~~6. 레이저 생성 쿨다운 감소~~ (완료)
~~7. 크리스탈 생성 쿨다운 감소~~ (완료)
~~8. 기본 체력 리젠율 설정~~ (완료)

**Comment by suhynnoh** [comment]
- 적 생성
  - ~~현재 0, 100, 200초로 100초 기준으로 적 생성 단계가 올라가는데 이를 50초로 세분화해도 좋을 것 같습니다~~ (완료)
  - ~~적 생성 주기가 시간 지남에 따라 더 짧아져도 될 것 같습니다~~ (이미 있는 기능)
- 함선
  - ~~궁극기 전체 비용을 줄여 더 자주 사용하면 좋을거같습니다~~ (완료)
  - ~~기본 사거리를 줄여 사거리 증가 아이템의 벨류를 높이면 좋을 것 같습니다~~ (완료)

**Comment by wjddml** [comment]
~~1. 보스의 변칙적인 방향 변경~~ (완료)
~~2. 함선별 기본 스탯 조정~~ (완료)
~~3. 총알 및 포탈 색상 조정~~ (필수 아님)

**Comment by Koominjae** [comment]
> * 적 생성
>   
>   * ~현재 0, 100, 200초로 100초 기준으로 적 생성 단계가 올라가는데 이를 50초로 세분화해도 좋을 것 같습니다~ (완료)
>   * 적 생성 주기가 시간 지남에 따라 더 짧아져도 될 것 같습니다
> * 함선
>   
>   * ~궁극기 전체 비용을 줄여 더 자주 사용하면 좋을거같습니다~ (완료)
>   * ~기본 사거리를 줄여 사거리 증가 아이템의 벨류를 높이면 좋을 것 같습니다~ (완료)

이미 생존 시간 10초 마다 적 생성 쿨타임 50ms씩 줄어들고 있긴 합니다. 크게 체감이 안된다고 하면 이것들을 조정하면 될 것 같습니다. 일단 디폴트 생성 주기 자체가 1.5초로 줄었기 때문에 따로 건들진 않겠습니다.

**Comment by Koominjae** [comment]
> 1. 보스의 변칙적인 방향 변경
> 2. 함선별 기본 스탯 조정
> 3. 총알 및 포탈 색상 조정

다른 패치들은 제 개인적으로 원했던 변경점이었거나 어떻게 바꾸기로 값이 정해져있던 것들인데 이 부분들은 저 혼자 임의로 건드리긴 애매한 부분들이라 원하시는 방향대로 수정해서 밸런스 패치 브랜치에 올려주시면 감사하겠습니다.
